#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sbsigntools
Version  : 0.9.1
Release  : 4
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/snapshot/sbsigntools-0.9.1.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/snapshot/sbsigntools-0.9.1.tar.gz
Source1  : https://github.com/rustyrussell/ccan/archive/b1f28e17227f2320d07fe052a8a48942fe17caa5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT
Requires: sbsigntools-bin
Requires: sbsigntools-doc
BuildRequires : binutils-dev
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : help2man
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(uuid)

%description
sbsigntool - Signing utility for UEFI secure boot
See file ./INSTALL for building and installation instructions.

%package bin
Summary: bin components for the sbsigntools package.
Group: Binaries

%description bin
bin components for the sbsigntools package.


%package doc
Summary: doc components for the sbsigntools package.
Group: Documentation

%description doc
doc components for the sbsigntools package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n sbsigntools-0.9.1
mkdir -p %{_topdir}/BUILD/sbsigntools-0.9.1/lib/ccan.git
mv %{_topdir}/BUILD/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/* %{_topdir}/BUILD/sbsigntools-0.9.1/lib/ccan.git

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510774964
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510774964
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sbattach
/usr/bin/sbkeysync
/usr/bin/sbsiglist
/usr/bin/sbsign
/usr/bin/sbvarsign
/usr/bin/sbverify

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
