#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : sbsigntools
Version  : 0.9.5
Release  : 10
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/snapshot/sbsigntools-0.9.5.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/snapshot/sbsigntools-0.9.5.tar.gz
Source1  : https://github.com/rustyrussell/ccan/archive/b1f28e17227f2320d07fe052a8a48942fe17caa5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT
Requires: sbsigntools-bin = %{version}-%{release}
Requires: sbsigntools-license = %{version}-%{release}
Requires: sbsigntools-man = %{version}-%{release}
BuildRequires : binutils-dev
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : gnu-efi-staticdev
BuildRequires : help2man
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(uuid)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
sbsigntool - Signing utility for UEFI secure boot
See file ./INSTALL for building and installation instructions.

%package bin
Summary: bin components for the sbsigntools package.
Group: Binaries
Requires: sbsigntools-license = %{version}-%{release}

%description bin
bin components for the sbsigntools package.


%package license
Summary: license components for the sbsigntools package.
Group: Default

%description license
license components for the sbsigntools package.


%package man
Summary: man components for the sbsigntools package.
Group: Default

%description man
man components for the sbsigntools package.


%prep
%setup -q -n sbsigntools-0.9.5
cd %{_builddir}
tar xf %{_sourcedir}/b1f28e17227f2320d07fe052a8a48942fe17caa5.tar.gz
cd %{_builddir}/sbsigntools-0.9.5
mkdir -p lib/ccan.git
cp -r %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/* %{_builddir}/sbsigntools-0.9.5/lib/ccan.git

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1688579247
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1688579247
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sbsigntools
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/alloc/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/antithread/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/asearch/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/asort/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/asprintf/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/autodata/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/avl/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/bdelta/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/block_pool/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/btree/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/cast/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ccan_tokenizer/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/f7cf250605f23eb5572eaa92f1b261c668cc0f6d || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/charset/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ciniparser/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/crc/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/crcsync/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/daemon_with_notify/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/f7cf250605f23eb5572eaa92f1b261c668cc0f6d || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/daemonize/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/darray/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/dgraph/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/failtest/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/foreach/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/grab_file/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/htable/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/idtree/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ilog/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/iscsi/LICENCE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/iscsi/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/jmap/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/jset/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/json/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/lbalance/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/likely/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/md4/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/net/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/nfs/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/objset/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ogg_to_pcm/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/opt/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ptr_valid/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/rbtree/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/read_write_all/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/sparse_bsearch/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/str_talloc/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/stringmap/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/f7cf250605f23eb5572eaa92f1b261c668cc0f6d || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/talloc/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/talloc_link/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/tally/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/time/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/tlist/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/ttxml/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/typesafe_cb/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccan-b1f28e17227f2320d07fe052a8a48942fe17caa5/ccan/wwviaudio/LICENSE %{buildroot}/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/sbsigntools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sbsigntools/2e42353f981d6faf41d53432b53cff0276850c0d || :
cp %{_builddir}/sbsigntools-%{version}/LICENSE.GPLv3 %{buildroot}/usr/share/package-licenses/sbsigntools/a6adc13d0c809ab8cb68e6e3b6eb7571bd0e2920 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sbattach
/usr/bin/sbkeysync
/usr/bin/sbsiglist
/usr/bin/sbsign
/usr/bin/sbvarsign
/usr/bin/sbverify

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sbsigntools/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/sbsigntools/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305
/usr/share/package-licenses/sbsigntools/2e42353f981d6faf41d53432b53cff0276850c0d
/usr/share/package-licenses/sbsigntools/842745cb706f8f2126506f544492f7a80dbe29b3
/usr/share/package-licenses/sbsigntools/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/sbsigntools/a6adc13d0c809ab8cb68e6e3b6eb7571bd0e2920
/usr/share/package-licenses/sbsigntools/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
/usr/share/package-licenses/sbsigntools/f7cf250605f23eb5572eaa92f1b261c668cc0f6d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/sbattach.1
/usr/share/man/man1/sbkeysync.1
/usr/share/man/man1/sbsiglist.1
/usr/share/man/man1/sbsign.1
/usr/share/man/man1/sbvarsign.1
/usr/share/man/man1/sbverify.1
